//! LLVM IR generation for kscr
//!
//! This crate provides conversion from kscr's IR to LLVM IR text format.
//! It generates LLVM IR as a string that can be compiled with `llc` or `clang`.
//!
//! Usage:
//! ```ignore
//! use kscr_llvm::LLVMIRGenerator;
//! 
//! let mut gen = LLVMIRGenerator::new("my_module");
//! gen.generate_placeholder_main();
//! println!("{}", gen.to_string());
//! ```

use std::fmt::Write;

/// LLVM IR generator that produces textual LLVM IR
pub struct LLVMIRGenerator {
    module_name: String,
    output: String,
    counter: usize,
}

impl LLVMIRGenerator {
    /// Create a new LLVM IR generator
    pub fn new(module_name: &str) -> Self {
        let mut gen = LLVMIRGenerator {
            module_name: module_name.to_string(),
            output: String::new(),
            counter: 0,
        };
        gen.emit_header();
        gen
    }

    /// Emit LLVM IR module header
    fn emit_header(&mut self) {
        writeln!(
            &mut self.output,
            "; ModuleID = '{}'",
            self.module_name
        )
        .unwrap();
        writeln!(&mut self.output, "source_filename = \"{}\"", self.module_name).unwrap();
        writeln!(&mut self.output, "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"").unwrap();
        writeln!(&mut self.output, "target triple = \"x86_64-unknown-linux-gnu\"").unwrap();
        writeln!(&mut self.output).unwrap();
    }

    /// Generate a new unique label/register
    fn gen_label(&mut self, prefix: &str) -> String {
        let id = self.counter;
        self.counter += 1;
        format!("{}{}", prefix, id)
    }

    /// Emit runtime function declarations
    fn emit_runtime_declarations(&mut self) {
        writeln!(&mut self.output, "; Runtime function declarations").unwrap();
        writeln!(&mut self.output).unwrap();

        // Thunk structure type: { i8*, i8*, i8*, i32 }
        writeln!(
            &mut self.output,
            "%struct.kscr_thunk = type {{ i8*, i8*, i8*, i32 }}"
        )
        .unwrap();
        writeln!(&mut self.output).unwrap();

        // Value structure type (tagged union): { i32, i8* }
        writeln!(&mut self.output, "%struct.kscr_value = type {{ i32, i8* }}").unwrap();
        writeln!(&mut self.output).unwrap();

        // Force thunk runtime function
        writeln!(
            &mut self.output,
            "declare %struct.kscr_value @kscr_force_thunk(%struct.kscr_thunk*)"
        )
        .unwrap();
        writeln!(&mut self.output).unwrap();

        // IO action executor
        writeln!(
            &mut self.output,
            "declare %struct.kscr_value @kscr_execute_io(%struct.kscr_value*)"
        )
        .unwrap();
        writeln!(&mut self.output).unwrap();

        // Memory allocation
        writeln!(&mut self.output, "declare i8* @malloc(i64)").unwrap();
        writeln!(&mut self.output).unwrap();

        // Standard C library functions
        writeln!(&mut self.output, "declare i32 @puts(i8*)").unwrap();
        writeln!(&mut self.output, "declare i32 @printf(i8*, ...)").unwrap();
        writeln!(&mut self.output).unwrap();
    }

    /// Generate a placeholder main function
    pub fn generate_placeholder_main(&mut self) {
        self.emit_runtime_declarations();

        // String constant for message
        let msg = "LLVM IR generated by kscr";
        writeln!(
            &mut self.output,
            "@.str = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
            msg.len() + 1,
            msg
        )
        .unwrap();
        writeln!(&mut self.output).unwrap();

        // Main function
        writeln!(&mut self.output, "define i32 @main() {{").unwrap();
        writeln!(&mut self.output, "entry:").unwrap();
        writeln!(
            &mut self.output,
            "  %0 = getelementptr inbounds [{} x i8], [{} x i8]* @.str, i64 0, i64 0",
            msg.len() + 1,
            msg.len() + 1
        )
        .unwrap();
        writeln!(&mut self.output, "  %1 = call i32 @puts(i8* %0)").unwrap();
        writeln!(&mut self.output, "  ret i32 0").unwrap();
        writeln!(&mut self.output, "}}").unwrap();
        writeln!(&mut self.output).unwrap();
    }

    /// Generate LLVM IR for integer arithmetic
    pub fn generate_integer_add_function(&mut self) {
        writeln!(&mut self.output, "; Integer addition function").unwrap();
        writeln!(
            &mut self.output,
            "define i64 @kscr_add_i64(i64 %a, i64 %b) {{"
        )
        .unwrap();
        writeln!(&mut self.output, "entry:").unwrap();
        writeln!(&mut self.output, "  %result = add i64 %a, %b").unwrap();
        writeln!(&mut self.output, "  ret i64 %result").unwrap();
        writeln!(&mut self.output, "}}").unwrap();
        writeln!(&mut self.output).unwrap();
    }

    /// Get the generated LLVM IR as a string
    pub fn to_string(&self) -> String {
        self.output.clone()
    }
}

/// Generate LLVM IR text for a module (simplified version)
/// This generates a placeholder main function as a proof of concept
pub fn generate_llvm_ir_text(module_name: &str) -> Result<String, String> {
    let mut gen = LLVMIRGenerator::new(module_name);
    gen.generate_placeholder_main();
    gen.generate_integer_add_function();
    Ok(gen.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_basic_llvm_ir() {
        let ir = generate_llvm_ir_text("test_module").unwrap();
        assert!(ir.contains("define i32 @main()"));
        assert!(ir.contains("LLVM IR generated by kscr"));
        assert!(ir.contains("ret i32 0"));
    }

    #[test]
    fn test_generator_has_runtime_declarations() {
        let mut gen = LLVMIRGenerator::new("test");
        gen.emit_runtime_declarations();
        let ir = gen.to_string();
        
        assert!(ir.contains("kscr_force_thunk"));
        assert!(ir.contains("kscr_execute_io"));
        assert!(ir.contains("malloc"));
        assert!(ir.contains("puts"));
    }

    #[test]
    fn test_generator_has_thunk_and_value_types() {
        let mut gen = LLVMIRGenerator::new("test");
        gen.emit_runtime_declarations();
        let ir = gen.to_string();
        
        assert!(ir.contains("%struct.kscr_thunk"));
        assert!(ir.contains("%struct.kscr_value"));
    }

    #[test]
    fn test_integer_add_function() {
        let mut gen = LLVMIRGenerator::new("test");
        gen.generate_integer_add_function();
        let ir = gen.to_string();
        
        assert!(ir.contains("define i64 @kscr_add_i64(i64 %a, i64 %b)"));
        assert!(ir.contains("add i64 %a, %b"));
    }
}
