[package]
name = "kscr_lsp"
version = "0.5.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "kscr-lsp"
path = "src/main.rs"

[dependencies]
kscr = { path = "../.." }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
